name: Build and push Docker images
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/yakweide/yakweide-website-v2:latest
      - name: Dependabot
        uses: dependabot/dependabot-core@latest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          directory: .
          update: "dependencies"
          schedule: "daily"