on:
  # Trigger the workflow for pull requests from your own repository
  pull_request:
    branches:
      - main
  # Trigger the workflow for pull requests from forked repositories
  pull_request_target:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ghcr.io/yakweide/yakweide-website-v2:latest
