# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

# Define the events that will trigger Dependabot
# In this example, the workflow will run on push events to the default branch
# and on a daily schedule
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"