on:
  pull_request_target:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ghcr.io/yakweide/yakweide-website-v2:latest
      - name: Run React Tests
        run: |
          docker run --rm -it -d -p 3000:3000 --name my-app ghcr.io/yakweide/yakweide-website-v2:latest
          docker exec my-app npm run test
          TEST_EXIT_CODE=$?
          docker stop my-app
          exit $TEST_EXIT_CODE
      - name: Check Test Results
        run: exit ${{ jobs.build.steps[2].outputs.exit_code }}
