on:
  pull_request_target:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.test
          push: false
          tags: ghcr.io/yakweide/yakweide-website-v2:latest
      - name: Run React Tests
        run: |
          docker run --rm -p 3000:3000 --name my-app ghcr.io/yakweide/yakweide-website-v2:latest sh -c "npm run test -- --watchAll=false"t
          TEST_EXIT_CODE=$?
          docker stop my-app
          echo "::set-output name=exit_code::$TEST_EXIT_CODE"
      - name: Check Test Results
        if: ${{ success() }}
        run: exit ${{ steps.Run-React-Tests.outputs.exit_code }}

